version: 1.2
workflows:
   - subclass: cwl
     topic: 'foobar'
     primaryDescriptorPath: /Dockstore.cwl
     testParameterFiles:
     - /test/dockstore2.cwl.json
     authors:
     - name: DockstoreYml Author 1
     - name: DockstoreYml Author 2
     - name: DockstoreYml Author 3
     - name: DockstoreYml Author 4
     #- orcid: 0000-0001-7641-7724
     - orcid: 0000-0002-6130-1021
     - name: Processed author
   # - subclass: badsubclass
   #   name: bad-workflow
   #   readMePath: /foo/README.md
   #   primaryDescriptorPath: /Dockstore.cwl
   #   testParameterFiles:
   #   - /test/dockstore2.cwl.json
   - subclass: cwl
     name: foo
     readMePath: /foo/README.md
     primaryDescriptorPath: /Dockstore.cwl
     testParameterFiles:
     - /test/dockstore2.cwl.json
   # - name: bad-workflow-2
   #   readMePath: /foo/README.md
   #   primaryDescriptorPath: /Dockstore.cwl
   #   testParameterFiles:
   #   - /test/dockstore2.cwl.json
