version: 1.2
workflows:
   - subclass: cwl
     topic: 'This is a manual GitHub Apps workflow topic'
     primaryDescriptorPath: /Dockstore.cwl
     testParameterFiles:
     - /test/dockstore2.cwl.json
     authors:
     - name: DockstoreYml Author 1
     #- orcid: 0000-0001-7641-7724
     - orcid: 0000-0002-6130-1021
     - name: Staging test
   - subclass: cwl
     topic: This is a different topic from the .dockstore.yml
     name: foo
     readMePath: /foo/README.md
     primaryDescriptorPath: /Dockstore.cwl
     authors:
     - name: sort entry name
     testParameterFiles:
     - /test/dockstore2.cwl.json
