version: 1.2
workflows:
   - subclass: cwl
     primaryDescriptorPath: /Dockstore.cwl
     testParameterFiles:
     - /test/dockstore2.cwl.json
    authors:
     - name: DockstoreYml Author
     - orcid: 1234-1234-1234-1234
   - subclass: cwl
     name: foo
     readMePath: /foo/README.md
     primaryDescriptorPath: /Dockstore.cwl
     testParameterFiles:
     - /test/dockstore2.cwl.json
