version: 1.2
workflows:
   - subclass: cwl
     primaryDescriptorPath: /Dockstore.cwl
     testParameterFiles:
     - /test/dockstore2.cwl.json
     authours:
     - orcid: 0000-0003-1072-5630 
     - orcid: 0000-0001-7641-7724 
     - name: Core update GH apps test
