on: 
  push:
    branches:
      - master

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions-ecosystem/action-push-tag@v1
        with:
          tag: bot-doi-alias
          message: 'Bot DOI alias test'


        
